# Generated by Django 2.0.3 on 2018-06-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(blank=True, choices=[('Inicio', 'Inicio'), ('Final', 'Final')], max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='procesos/%Y/%m/%d/')),
                ('estado_proceso', models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='Rastreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rastreo',
                'verbose_name_plural': 'rastreos',
                'ordering': ('creado',),
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='rastreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='rastreos.Rastreo'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='responsable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil'),
        ),
    ]
