# Generated by Django 2.0.3 on 2018-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado_proceso',
            field=models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255, null=True),
        ),
    ]
