# Generated by Django 2.0.3 on 2018-07-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0004_auto_20180629_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo_proceso',
            field=models.CharField(blank=True, choices=[('proceso 1', 'proceso 1'), ('proceso 2', 'proceso 2'), ('proceso 3', 'proceso 3'), ('proceso 4', 'proceso 4'), ('proceso 5', 'proceso 5'), ('proceso 6', 'proceso 6'), ('proceso 7', 'proceso 7')], max_length=255, null=True),
        ),
    ]
