# Generated by Django 2.0.3 on 2018-07-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0006_rastreo_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='responsable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil'),
        ),
    ]
