# Generated by Django 2.0.3 on 2018-07-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0008_proceso_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='rastreo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastreos', to='users.Perfil'),
        ),
    ]
