# Generated by Django 2.0.3 on 2018-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0009_auto_20180703_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo_proceso',
            field=models.CharField(blank=True, choices=[('Proceso 1', 'Proceso 1'), ('Proceso 2', 'Proceso 2'), ('Proceso 3', 'Proceso 3'), ('Proceso 4', 'Proceso 4'), ('Proceso 5', 'Proceso 5'), ('Proceso 6', 'Proceso 6'), ('Proceso 7', 'Proceso 7')], max_length=255, null=True),
        ),
    ]
