# Generated by Django 2.0.3 on 2018-07-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreos', '0010_auto_20180705_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo_proceso',
            field=models.CharField(blank=True, choices=[('Grupo HW', 'Grupo HW'), ('MBB', 'MBB'), ('TCC', 'TCC'), ('MBB Offerts', 'MBB Offerts'), ('F&C', 'F&C'), ('Logistica', 'Logistica'), ('Factory', 'Factory')], max_length=255, null=True),
        ),
    ]
