# Generated by Django 2.0.3 on 2018-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='contenido',
        ),
        migrations.AddField(
            model_name='tarea',
            name='ejecutar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
