# Generated by Django 2.0.3 on 2018-07-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20180717_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
