# Generated by Django 2.0.3 on 2018-07-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_tarea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='grupo_tarea',
            field=models.CharField(blank=True, choices=[('Formato Abastecimiento', 'Formato Abastecimiento')], max_length=255, null=True),
        ),
    ]
