# Generated by Django 2.0.3 on 2018-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_tarea_grupo_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo tarea',
                'verbose_name_plural': 'grupos tarea',
                'ordering': ('creado',),
            },
        ),
    ]
