# Generated by Django 2.0.3 on 2018-07-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_grupotarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='grupo_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tareas.GrupoTarea'),
        ),
    ]
