# Generated by Django 2.0.3 on 2018-04-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0003_auto_20180403_1725'),
        ('partes', '0003_auto_20180405_0956'),
        ('proyecciones', '0004_remove_proyeccion_rfe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsa', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('comunidades', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('satelital', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('lsm', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('calculo_hw', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('impactar', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_actividades', to='estaciones.Estacion')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_actividades', to='partes.Parte')),
                ('proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_actividades', to='proyecciones.Proyeccion')),
            ],
            options={
                'verbose_name': 'hw actividad',
                'verbose_name_plural': 'hw actividades',
                'ordering': ('creado',),
            },
        ),
    ]
