# Generated by Django 2.0.3 on 2018-05-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwactividad',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_actividades', to='estaciones.Estacion'),
        ),
    ]
