# Generated by Django 2.0.3 on 2018-04-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwactividad',
            name='proyeccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecciones.Proyeccion'),
        ),
    ]
