# Generated by Django 2.0.3 on 2018-04-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0002_auto_20180405_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwactividad',
            name='bolsa',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='comunidades',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='satelital',
        ),
    ]
