# Generated by Django 2.0.3 on 2018-04-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0003_auto_20180406_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwactividad',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_actividades', to='partes.Parte'),
        ),
    ]
