# Generated by Django 2.0.3 on 2018-05-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0004_auto_20180512_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwactividad',
            name='proyeccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecciones.Proyeccion'),
        ),
    ]
