# Generated by Django 2.0.3 on 2018-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0005_auto_20180512_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwactividad',
            name='agrupadores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='banda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='bolsa',
            field=models.CharField(blank=True, choices=[('', '---------'), ('55 sitios LSM', '55 sitios LSM'), ('165 sitios LSM', '165 sitios LSM'), ('170 sitios LSM', '170 sitios LSM'), ('485 sitios', '485 sitios'), ('531 sitios LSM', '531 sitios LSM'), ('Reemplazo 531', 'Reemplazo 531'), ('Sitios Bulk', 'Sitios Bulk'), ('AIRSCALE', 'AIRSCALE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='cantidad_estimada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='comunidades',
            field=models.CharField(blank=True, choices=[('', '---------'), ('142 Comunidades P1', '142 Comunidades P1'), ('142 Comunidades P1', '142 Comunidades P2'), ('142 Comunidades P1', '142 Comunidades P3')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='escenario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='grupo_parte',
            field=models.CharField(blank=True, choices=[('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Centro', 'Centro'), ('Costa', 'Costa'), ('Oriente', 'Oriente'), ('Occidente', 'Occidente'), ('Nor Oriente', 'Nor Oriente'), ('Nor Occidente', 'Nor Occidente'), ('Sur Oriente', 'Sur Oriente'), ('Sur Occidente', 'Sur Occidente')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='satelital',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Satelital', 'Satelital')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='w_fc_imp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwactividad',
            name='w_fc_sal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
