# Generated by Django 2.0.3 on 2018-05-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0006_auto_20180515_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwactividad',
            name='agrupadores',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='bolsa',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='cantidad_estimada',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='comunidades',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='escenario',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='grupo_parte',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='region',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='satelital',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='w_fc_imp',
        ),
        migrations.RemoveField(
            model_name='hwactividad',
            name='w_fc_sal',
        ),
    ]
