# Generated by Django 2.0.3 on 2018-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0008_hwactividad_cambiar_impactar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwactividad',
            name='proyeccion_extra',
        ),
    ]
