# Generated by Django 2.0.3 on 2018-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('parte_nokia', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('capex', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_parte', models.CharField(choices=[('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parte',
                'verbose_name_plural': 'partes',
                'ordering': ('creado',),
            },
        ),
    ]
