# Generated by Django 2.0.3 on 2018-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='parte_nokia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
