# Generated by Django 2.0.3 on 2018-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0002_parte_impactar'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='grupo_familia',
            field=models.CharField(blank=True, choices=[('TRI-BAND GSM/UMTS/LTE 8 PUERTOS ANTENA PEQUEÑA', 'TRI-BAND GSM/UMTS/LTE 8 PUERTOS ANTENA PEQUEÑA'), ('TRI-BAND GSM/UMTS/LTE 8 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 8 PUERTOS'), ('TRI-BAND GSM/UMTS/LTE 10 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 10 PUERTOS'), ('TRI-BAND GSM/UMTS/LTE 6 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 6 PUERTOS'), ('DUAL BAND GSM/UMTS 4 PUERTOS', 'DUAL BAND GSM/UMTS 4 PUERTOS'), ('SINGLE BAND LTE 2 PUERTOS', 'SINGLE BAND LTE 2 PUERTOS'), ('DUAL BAND GSM/UMTS/LTE 6 PUERTOS', 'DUAL BAND GSM/UMTS/LTE 6 PUERTOS'), ('DUAL BAND GSM/UMTS/LTE 4 PUERTOS', 'DUAL BAND GSM/UMTS/LTE 4 PUERTOS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='grupo_numero',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
