# Generated by Django 2.0.3 on 2018-04-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0003_auto_20180405_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='grupo_parte',
            field=models.CharField(blank=True, choices=[('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True),
        ),
    ]
