# Generated by Django 2.0.3 on 2018-04-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_auto_20180406_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='parte_nokia',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
