# Generated by Django 2.0.9 on 2018-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0005_auto_20180806_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='cod_sap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
