# Generated by Django 2.0.7 on 2018-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('idadicionales_hw_sv', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('wp', models.BigIntegerField(blank=True, null=True)),
                ('siteName', models.CharField(blank=True, max_length=60, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=45, null=True)),
                ('banda', models.CharField(blank=True, max_length=45, null=True)),
                ('escenario', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('parte', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.FloatField(blank=True, default=None, null=True)),
                ('proceso', models.CharField(blank=True, max_length=210, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_pedido', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('id', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'adicional',
                'verbose_name_plural': 'adicionales',
                'ordering': ('creado',),
            },
        ),
    ]
