# Generated by Django 2.0.7 on 2018-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
