# Generated by Django 2.0.7 on 2018-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0002_auto_20180907_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='idadicionales_hw_sv',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
