# Generated by Django 2.0.7 on 2018-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0003_auto_20180907_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='idadicionales_hw_sv',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
