# Generated by Django 2.0.7 on 2018-09-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0004_auto_20180914_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ('idadicionales_hw_sv',), 'verbose_name': 'adicional', 'verbose_name_plural': 'adicionales'},
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='subestado',
        ),
    ]
