# Generated by Django 2.0.7 on 2018-09-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180705_1834'),
        ('adicionales', '0005_auto_20180917_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ('-fecha_pedido',), 'verbose_name': 'adicional', 'verbose_name_plural': 'adicionales'},
        ),
        migrations.AddField(
            model_name='adicional',
            name='asignado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='adicional',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='recibido',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='adicional',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='users.Perfil'),
        ),
    ]
