# Generated by Django 2.0.7 on 2018-09-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicionales', '0006_auto_20180918_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='asignado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='recibido',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=255, null=True),
        ),
    ]
