# Generated by Django 2.0.3 on 2018-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HwEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('scope_claro', models.CharField(blank=True, max_length=150, null=True)),
                ('proyeccion_instalacion', models.DateField(blank=True, null=True)),
                ('w_proyeccion_instalacion', models.IntegerField(blank=True, null=True)),
                ('actividades', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'hw estacion',
                'verbose_name_plural': 'hw estaciones',
                'db_table': 'estaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HwParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_capex', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_nokia', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_capex', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion_parte', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'hw parte',
                'verbose_name_plural': 'hw partes',
                'db_table': 'partes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HwProyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(blank=True, max_length=80, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=19, null=True)),
                ('escenario', models.CharField(blank=True, max_length=20, null=True)),
                ('banda', models.CharField(blank=True, max_length=30, null=True)),
                ('agrupadores', models.CharField(blank=True, max_length=255, null=True)),
                ('rfe', models.DateField(blank=True, null=True)),
                ('parte', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, default='Pendiente', max_length=45, null=True)),
                ('cantidad_estimada', models.BigIntegerField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'hw proyeccion',
                'verbose_name_plural': 'hw proyecciones',
                'db_table': 'hw',
                'managed': False,
            },
        ),
    ]
