# Generated by Django 2.0.3 on 2018-04-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hwproyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(blank=True, max_length=80, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=19, null=True)),
                ('escenario', models.CharField(blank=True, max_length=20, null=True)),
                ('banda', models.CharField(blank=True, max_length=30, null=True)),
                ('agrupadores', models.CharField(blank=True, max_length=255, null=True)),
                ('RFE', models.DateField(blank=True, null=True)),
                ('parte', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, default='Pendiente', max_length=45, null=True)),
                ('cantidad_estimada', models.BigIntegerField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'hw proyeccion',
                'verbose_name_plural': 'hw proyecciones',
                'db_table': 'hw',
                'managed': False,
            },
        ),
    ]
