# Generated by Django 2.0.7 on 2018-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwControlRfe',
            fields=[
                ('id_hw_config', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.BigIntegerField(blank=True, default=0, null=True)),
                ('siteName', models.CharField(blank=True, max_length=60, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=30, null=True)),
                ('escenario', models.CharField(blank=True, max_length=20, null=True)),
                ('banda', models.CharField(blank=True, max_length=30, null=True)),
                ('seccion', models.CharField(blank=True, max_length=45, null=True)),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('parte', models.CharField(blank=True, max_length=45, null=True)),
                ('total_smr', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fuente', models.CharField(blank=True, max_length=45, null=True)),
                ('RFE', models.DateField(blank=True, null=True)),
                ('so', models.CharField(blank=True, max_length=255, null=True)),
                ('po', models.CharField(blank=True, max_length=255, null=True)),
                ('bodega_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('bodega_origen_fecha', models.DateField(blank=True, null=True)),
                ('issue_bodega_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('material_sobrante', models.TextField(blank=True, null=True)),
                ('bts_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reemplazo', models.CharField(blank=True, max_length=255, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('so_date', models.DateField(blank=True, null=True)),
                ('envio_capex', models.DateField(blank=True, null=True)),
                ('last_updated_ghw', models.DateField(blank=True, null=True)),
                ('homologacion', models.CharField(blank=True, max_length=85, null=True)),
            ],
            options={
                'verbose_name': 'hw control rfe',
                'verbose_name_plural': 'hw control rfe',
                'db_table': 'hw_control_rfe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HwSiteList',
            fields=[
                ('idsitesList', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=20, null=True)),
                ('proyeccion_instalacion', models.DateField(blank=True, null=True)),
                ('W_Proyeccion_Instalacion', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_claro', models.CharField(blank=True, max_length=150, null=True)),
                ('Bolsa_HW', models.CharField(blank=True, max_length=255, null=True)),
                ('w_fc_c', models.PositiveIntegerField(blank=True, null=True)),
                ('status_nokia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_HW', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'hw sitelist',
                'verbose_name_plural': 'hw sitelist',
                'db_table': 'sitesList_hw',
                'managed': False,
            },
        ),
    ]
