# Generated by Django 2.0.9 on 2018-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_proyecciones', '0002_hwcontrolrfe_hwsitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillDown',
            fields=[
                ('id_drill_down_d1', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Implemented', models.CharField(blank=True, max_length=255, null=True)),
                ('TSS', models.CharField(blank=True, max_length=255, null=True)),
                ('RFIC', models.IntegerField(blank=True, null=True)),
                ('FC_RFIC', models.IntegerField(blank=True, null=True)),
                ('CPO_Status1', models.CharField(blank=True, max_length=255, null=True)),
                ('CPO_Status2', models.CharField(blank=True, max_length=255, null=True)),
                ('HW_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('FC_HW', models.IntegerField(blank=True, null=True)),
                ('Status_Despachos', models.CharField(blank=True, max_length=255, null=True)),
                ('FC_Antenas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DrillDown',
                'verbose_name_plural': 'DrillDown',
                'db_table': 'DrillDown_D1',
                'managed': False,
            },
        ),
    ]
