# Generated by Django 2.0.3 on 2018-04-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0002_auto_20180419_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impacto',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impactos', to='partes.Parte'),
        ),
    ]
