# Generated by Django 2.0.3 on 2018-04-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0003_auto_20180419_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='impacto',
            name='impactado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True),
        ),
    ]
