# Generated by Django 2.0.3 on 2018-05-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactos', '0004_auto_20180516_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impacto',
            name='bolsa',
            field=models.CharField(blank=True, choices=[('', '---------'), ('55 sitios LSM', '55 sitios LSM'), ('165 sitios LSM', '165 sitios LSM'), ('170 sitios LSM', '170 sitios LSM'), ('485 sitios', '485 sitios'), ('531 sitios LSM', '531 sitios LSM'), ('Reemplazo 531', 'Reemplazo 531'), ('Sitios Bulk', 'Sitios Bulk'), ('AIRSCALE', 'AIRSCALE'), ('AIRSCALE 240', 'AIRSCALE 240')], max_length=255, null=True),
        ),
    ]
