# Generated by Django 2.0.3 on 2018-04-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoclaro',
            name='grupo_parte',
            field=models.CharField(blank=True, choices=[('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumonokia',
            name='grupo_parte',
            field=models.CharField(blank=True, choices=[('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consumoclaro',
            name='parte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
        migrations.AlterField(
            model_name='consumonokia',
            name='parte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
    ]
