# Generated by Django 2.0.3 on 2018-05-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoclaro',
            name='parte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
        migrations.AlterField(
            model_name='consumonokia',
            name='parte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
    ]
