""" GRUPO_PARTE_CHOICES  """
GRUPO_PARTE_CHOICES = (
    ('', '---------'),
    ('Accesorios', 'Accesorios'),
    ('Modulos', 'Modulos'),
    ('Antenas', 'Antenas'),
)

GRUPO_FAMILIA_CHOICES = (
    ('TRI-BAND GSM/UMTS/LTE 8 PUERTOS ANTENA PEQUEÑA', 'TRI-BAND GSM/UMTS/LTE 8 PUERTOS ANTENA PEQUEÑA'),
    ('TRI-BAND GSM/UMTS/LTE 8 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 8 PUERTOS'),
    ('TRI-BAND GSM/UMTS/LTE 10 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 10 PUERTOS'),
    ('TRI-BAND GSM/UMTS/LTE 6 PUERTOS', 'TRI-BAND GSM/UMTS/LTE 6 PUERTOS'),
    ('DUAL BAND GSM/UMTS 4 PUERTOS', 'DUAL BAND GSM/UMTS 4 PUERTOS'),
    ('SINGLE BAND LTE 2 PUERTOS', 'SINGLE BAND LTE 2 PUERTOS'),
    ('DUAL BAND GSM/UMTS/LTE 6 PUERTOS', 'DUAL BAND GSM/UMTS/LTE 6 PUERTOS'),
    ('DUAL BAND GSM/UMTS/LTE 4 PUERTOS', 'DUAL BAND GSM/UMTS/LTE 4 PUERTOS'),
)

GRUPO_NUMERO_CHOICES = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
)

""" IMPACTAR_CHOICES  """
IMPACTAR_CHOICES = (
    ('Si', 'Si'),
    ('No', 'No'),
)
