# Generated by Django 2.0.3 on 2018-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, unique=True)),
                ('region', models.CharField(choices=[('Centro', 'Centro'), ('Costa', 'Costa'), ('Oriente', 'Oriente'), ('Occidente', 'Occidente'), ('Nor Oriente', 'Nor Oriente'), ('Nor Occidente', 'Nor Occidente'), ('Sur Oriente', 'Sur Oriente'), ('Sur Occidente', 'Sur Occidente')], max_length=255)),
                ('scope_claro', models.CharField(blank=True, choices=[('Scope 2018', 'Scope 2018'), ('Scope 2017', 'Scope 2017'), ('Scope 2018 Integrado 2017', 'Scope 2018 Integrado 2017'), ('Scope 300LTE', 'Scope 300LTE'), ('Fuera Alcance', 'Fuera Alcance'), ('x Sale x', 'x Sale x')], max_length=255, null=True)),
                ('w_fc_imp', models.PositiveIntegerField(blank=True, null=True)),
                ('w_fc_sal', models.PositiveIntegerField(blank=True, null=True)),
                ('total_actividades', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_wr', models.CharField(blank=True, choices=[('Integrado', 'Integrado'), ('On_Air', 'On_Air'), ('Solicitud_Abastecimiento', 'Solicitud_Abastecimiento'), ('Instalado', 'Instalado'), ('Solicitud_Partes_Capex', 'Solicitud_Partes_Capex'), ('Actividad_Adicional', 'Actividad_Adicional'), ('Desmonte Equipos', 'Desmonte Equipos'), ('En_Instalacion', 'En_Instalacion'), ('En_Integracion', 'En_Integracion'), ('HW_Recibido', 'HW_Recibido'), ('Revisar_Pendientes', 'Revisar_Pendientes'), ('Acceso_Administrativo', 'Acceso_Administrativo'), ('Permiso_Acceso', 'Permiso_Acceso'), ('Performance_SS', 'Performance_SS'), ('Detenido_Cosite', 'Detenido_Cosite'), ('Pendiente_RFE', 'Pendiente_RFE'), ('Detenido_TSS', 'Detenido_TSS'), ('En_Transito', 'En_Transito'), ('TX', 'TX'), ('Pendiente_RFD', 'Pendiente_RFD'), ('Pendiente_RSH', 'Pendiente_RSH'), ('En_Programacion', 'En_Programacion'), ('Pendiente_HW', 'Pendiente_HW'), ('Solicitud_Despacho', 'Solicitud_Despacho'), ('Despacho_Solicitado', 'Despacho_Solicitado'), ('TSS', 'TSS'), ('Detenido_Antena', 'Detenido_Antena'), ('Detenido_Acceso', 'Detenido_Acceso'), ('HW_Antena', 'HW_Antena'), ('Aprovisionamiento', 'Aprovisionamiento'), ('Detenido_Acceso_Reemplazar_Sitio', 'Detenido_Acceso_Reemplazar_Sitio'), ('HW', 'HW'), ('HSEQ', 'HSEQ'), ('Correccion_Agrupador', 'Correccion_Agrupador'), ('OnAir_Comunidades', 'OnAir_Comunidades'), ('CW_Claro', 'CW_Claro'), ('En_Programacion_ReportadoPreviamente', 'En_Programacion_ReportadoPreviamente'), ('Aval_Segunda_Visita', 'Aval_Segunda_Visita'), ('RSH', 'RSH'), ('Scope_Sale', 'Scope_Sale'), ('Error_Claro', 'Error_Claro'), ('Otros O&M', 'Otros O&M'), ('Evaluacion_Estructural', 'Evaluacion_Estructural'), ('Sin_ID_Abastecimiento', 'Sin_ID_Abastecimiento'), ('OV_LTE_CE', 'OV_LTE_CE'), ('Reactivado', 'Reactivado'), ('Detenido_Robo', 'Detenido_Robo'), ('Instalacion_ReportadaPreviamente', 'Instalacion_ReportadaPreviamente'), ('Material_Faltante', 'Material_Faltante'), ('Antena', 'Antena'), ('Cancelado_Claro', 'Cancelado_Claro'), ('Congelado', 'Congelado'), ('Detenido_Orden_Publico', 'Detenido_Orden_Publico'), ('HW_Parcial', 'HW_Parcial'), ('Cancelado', 'Cancelado'), ('Programacion_Pendiente2016', 'Programacion_Pendiente2016'), ('Detenido_HSEQ', 'Detenido_HSEQ')], max_length=255, null=True)),
                ('mos', models.DateField(blank=True, null=True)),
                ('bolsa', models.CharField(blank=True, choices=[('', '---------'), ('45 sitios LSM', '45 sitios LSM'), ('120 sitios LSM', '120 sitios LSM'), ('128 sitios LSM', '128 sitios LSM'), ('485 sitios', '485 sitios'), ('531 sitios LSM', '531 sitios LSM'), ('Reemplazo 531', 'Reemplazo 531'), ('Sitios Bulk', 'Sitios Bulk')], max_length=255, null=True)),
                ('comunidades', models.CharField(blank=True, choices=[('', '---------'), ('142 Comunidades P1', '142 Comunidades P1'), ('142 Comunidades P1', '142 Comunidades P2'), ('142 Comunidades P1', '142 Comunidades P3')], max_length=255, null=True)),
                ('satelital', models.CharField(blank=True, choices=[('', '---------'), ('Satelital', 'Satelital')], max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estacion',
                'verbose_name_plural': 'estaciones',
                'ordering': ('creado',),
            },
        ),
    ]
