# Generated by Django 2.0.3 on 2018-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='nombre',
            new_name='site_name',
        ),
        migrations.RenameField(
            model_name='estacion',
            old_name='actividades',
            new_name='total_actividades',
        ),
        migrations.RenameField(
            model_name='estacion',
            old_name='fc_imp',
            new_name='w_fc_imp',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='estado_rfe',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='fc_wr',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='fc_wr_y',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='scope',
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_wr',
            field=models.CharField(blank=True, choices=[('Integrado', 'Integrado'), ('On_Air', 'On_Air'), ('Solicitud_Abastecimiento', 'Solicitud_Abastecimiento'), ('Instalado', 'Instalado'), ('Solicitud_Partes_Capex', 'Solicitud_Partes_Capex'), ('Actividad_Adicional', 'Actividad_Adicional'), ('Desmonte Equipos', 'Desmonte Equipos'), ('En_Instalacion', 'En_Instalacion'), ('En_Integracion', 'En_Integracion'), ('HW_Recibido', 'HW_Recibido'), ('Revisar_Pendientes', 'Revisar_Pendientes'), ('Acceso_Administrativo', 'Acceso_Administrativo'), ('Permiso_Acceso', 'Permiso_Acceso'), ('Performance_SS', 'Performance_SS'), ('Detenido_Cosite', 'Detenido_Cosite'), ('Pendiente_RFE', 'Pendiente_RFE'), ('Detenido_TSS', 'Detenido_TSS'), ('En_Transito', 'En_Transito'), ('TX', 'TX'), ('Pendiente_RFD', 'Pendiente_RFD'), ('Pendiente_RSH', 'Pendiente_RSH'), ('En_Programacion', 'En_Programacion'), ('Pendiente_HW', 'Pendiente_HW'), ('Solicitud_Despacho', 'Solicitud_Despacho'), ('Despacho_Solicitado', 'Despacho_Solicitado'), ('TSS', 'TSS'), ('Detenido_Antena', 'Detenido_Antena'), ('Detenido_Acceso', 'Detenido_Acceso'), ('HW_Antena', 'HW_Antena'), ('Aprovisionamiento', 'Aprovisionamiento'), ('Detenido_Acceso_Reemplazar_Sitio', 'Detenido_Acceso_Reemplazar_Sitio'), ('HW', 'HW'), ('HSEQ', 'HSEQ'), ('Correccion_Agrupador', 'Correccion_Agrupador'), ('OnAir_Comunidades', 'OnAir_Comunidades'), ('CW_Claro', 'CW_Claro'), ('En_Programacion_ReportadoPreviamente', 'En_Programacion_ReportadoPreviamente'), ('Aval_Segunda_Visita', 'Aval_Segunda_Visita'), ('RSH', 'RSH'), ('Scope_Sale', 'Scope_Sale'), ('Error_Claro', 'Error_Claro'), ('Otros O&M', 'Otros O&M'), ('Evaluacion_Estructural', 'Evaluacion_Estructural'), ('Sin_ID_Abastecimiento', 'Sin_ID_Abastecimiento'), ('OV_LTE_CE', 'OV_LTE_CE'), ('Reactivado', 'Reactivado'), ('Detenido_Robo', 'Detenido_Robo'), ('Instalacion_ReportadaPreviamente', 'Instalacion_ReportadaPreviamente'), ('Material_Faltante', 'Material_Faltante'), ('Antena', 'Antena'), ('Cancelado_Claro', 'Cancelado_Claro'), ('Congelado', 'Congelado'), ('Detenido_Orden_Publico', 'Detenido_Orden_Publico'), ('HW_Parcial', 'HW_Parcial'), ('Cancelado', 'Cancelado'), ('Programacion_Pendiente2016', 'Programacion_Pendiente2016'), ('Detenido_HSEQ', 'Detenido_HSEQ')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='scope_claro',
            field=models.CharField(blank=True, choices=[('Scope 2018', 'Scope 2018'), ('Scope 2017', 'Scope 2017'), ('Scope 2018 Integrado 2017', 'Scope 2018 Integrado 2017'), ('Scope 300LTE', 'Scope 300LTE'), ('Fuera Alcance', 'Fuera Alcance'), ('x Sale x', 'x Sale x')], max_length=255, null=True),
        ),
    ]
