# Generated by Django 2.0.3 on 2018-04-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_auto_20180402_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='mos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='w_fc_sal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
