# Generated by Django 2.0.3 on 2018-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0006_auto_20180511_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Centro', 'Centro'), ('Costa', 'Costa'), ('Oriente', 'Oriente'), ('Occidente', 'Occidente'), ('Nor Oriente', 'Nor Oriente'), ('Nor Occidente', 'Nor Occidente'), ('Sur Oriente', 'Sur Oriente'), ('Sur Occidente', 'Sur Occidente')], max_length=255, null=True),
        ),
    ]
