# Generated by Django 2.0.3 on 2018-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0008_auto_20180515_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='impactar',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=255),
        ),
    ]
