# Generated by Django 2.0.3 on 2018-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_auto_20180516_0802'),
        ('estaciones', '0010_auto_20180518_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='partes',
            field=models.ManyToManyField(to='partes.Parte'),
        ),
    ]
