# Generated by Django 2.0.3 on 2018-06-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0023_estacion_status_nokia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='status_nokia',
            field=models.CharField(blank=True, choices=[('Custom Clearance', 'Custom Clearance'), ('Complete Sites (Installed)', 'Complete Sites (Installed)'), ('Waiting CSP Configuration', 'Waiting CSP Configuration'), ('Pending Project HW Request', 'Pending Project HW Request'), ('To Dispatch', 'To Dispatch'), ('Waiting Factory Feedback', 'Waiting Factory Feedback')], max_length=255, null=True),
        ),
    ]
