# Generated by Django 2.0.3 on 2018-06-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0024_auto_20180613_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitacoraEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vitacora', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitacoras_estacion', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'vitacora estacion',
                'verbose_name_plural': 'vitacoras estacion',
                'ordering': ('creado',),
            },
        ),
    ]
