# Generated by Django 2.0.3 on 2018-06-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0025_vitacoraestacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bitacora', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_estacion', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'bitacora estacion',
                'verbose_name_plural': 'bitacoras estacion',
                'ordering': ('creado',),
            },
        ),
        migrations.RemoveField(
            model_name='vitacoraestacion',
            name='estacion',
        ),
        migrations.DeleteModel(
            name='VitacoraEstacion',
        ),
    ]
