# Generated by Django 2.0.3 on 2018-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0026_auto_20180619_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
