# Generated by Django 2.0.3 on 2018-07-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0029_auto_20180710_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyeccion', models.CharField(blank=True, choices=[('Entro', 'Entro'), ('Salio', 'Salio')], max_length=255, null=True)),
                ('fecha_proyeccion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_estacion', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'proyecion estacion',
                'verbose_name_plural': 'proyeciones estacion',
                'ordering': ('creado',),
            },
        ),
    ]
