# Generated by Django 2.0.3 on 2018-05-29 20:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('tipo_consulta', models.CharField(blank=True, choices=[('', '---------'), ('Raw', 'Raw'), ('Custom', 'Custom')], max_length=255, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ('creado',),
            },
        ),
    ]
