# Generated by Django 2.0.7 on 2018-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20180614_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='database',
            field=models.CharField(blank=True, choices=[('', '---------'), ('default', 'default'), ('nokiagi_db', 'nokiagi_db')], max_length=255, null=True),
        ),
    ]
