# Generated by Django 2.0.7 on 2018-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='database',
            field=models.CharField(choices=[('', '---------'), ('default', 'default'), ('nokiagi_db', 'nokiagi_db')], default='default', max_length=255),
        ),
    ]
