# Generated by Django 2.0.7 on 2018-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_auto_20180828_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('', '---------'), ('Raw', 'Raw'), ('Custom', 'Custom')], default='Custom', max_length=255),
        ),
    ]
