# Generated by Django 2.0.3 on 2018-04-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='proyeccion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proyeccion',
            name='hw_proyeccion',
        ),
    ]
