# Generated by Django 2.0.3 on 2018-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='estado_proyeccion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No Aprobado', 'NO Aprobado')], max_length=255),
        ),
    ]
