# Generated by Django 2.0.3 on 2018-05-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0002_auto_20180427_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='estaciones.Estacion'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='estado_proyeccion',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado')], max_length=255, null=True),
        ),
    ]
