# Generated by Django 2.0.3 on 2018-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0003_auto_20180404_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyeccion',
            name='rfe',
        ),
    ]
