# Generated by Django 2.0.3 on 2018-05-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0005_auto_20180511_1009'),
        ('partes', '0003_auto_20180509_1605'),
        ('proyecciones', '0003_auto_20180503_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('banda', models.CharField(blank=True, max_length=255, null=True)),
                ('agrupadores', models.CharField(blank=True, max_length=255, null=True)),
                ('rfe', models.DateField(blank=True, null=True)),
                ('estado_proyeccion', models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado')], max_length=255, null=True)),
                ('cantidad_estimada', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_extra', to='estaciones.Estacion')),
                ('parte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones_extra', to='partes.Parte')),
            ],
            options={
                'verbose_name': 'proyeccion extra',
                'verbose_name_plural': 'proyecciones extra',
                'ordering': ('creado',),
            },
        ),
    ]
