# Generated by Django 2.0.3 on 2018-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_actividades', '0009_remove_hwactividad_proyeccion_extra'),
        ('proyecciones', '0004_proyeccionextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyeccionextra',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='proyeccionextra',
            name='parte',
        ),
        migrations.DeleteModel(
            name='ProyeccionExtra',
        ),
    ]
