# Generated by Django 2.0.3 on 2018-04-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0005_auto_20180406_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyeccion',
            name='rfe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
