# Generated by Django 2.0.3 on 2018-04-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0008_auto_20180412_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proyeccion',
            unique_together=set(),
        ),
    ]
