# Generated by Django 2.0.3 on 2018-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0009_auto_20180413_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='hw_proyeccion',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
