# Generated by Django 2.0.3 on 2018-04-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0010_auto_20180413_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='hw_proyeccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proyeccion',
            unique_together={('id', 'hw_proyeccion')},
        ),
    ]
