# Generated by Django 2.0.3 on 2018-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llegadas', '0002_auto_20180503_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llegada',
            name='grupo_parte',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True),
        ),
    ]
