""" TIPO_IMPACTO_CHOICES """
TIPO_IMPACTO_CHOICES = (
    ('ANTENA', 'ANTENA'),
    ('MODULO - ACCESORIO', 'MODULO - ACCESORIO'),
    ('MODULO - ACCESORIO - ANTENA', 'MODULO - ACCESORIO - ANTENA'),
)

""" IMPACTADO_CHOICES  """
IMPACTADO_CHOICES = (
    ('Si', 'Si'),
    ('No', 'No'),
)
