""" TIPO_IMPACTO_CHOICES """
TIPO_IMPACTO_CHOICES = (
    ('MODULO-ACCESORIO', 'MODULO-ACCESORIO'),
    ('ANTENA', 'ANTENA'),
    ('MODULO-ACCESORIO-ANTENA', 'MODULO-ACCESORIO-ANTENA'),
)

""" IMPACTADO_CHOICES  """
IMPACTADO_CHOICES = (
    ('Si', 'Si'),
    ('No', 'No'),
)
