# Generated by Django 2.0.7 on 2018-07-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0030_proyeccionestacion'),
        ('partes', '0004_auto_20180516_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.PositiveIntegerField(blank=True, null=True)),
                ('capex', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('cod_bodega', models.CharField(blank=True, max_length=255, null=True)),
                ('bodega', models.CharField(blank=True, max_length=255, null=True)),
                ('familia', models.PositiveIntegerField(blank=True, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=255, null=True)),
                ('puertos', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('parte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte')),
            ],
            options={
                'verbose_name': 'asignacion antena',
                'verbose_name_plural': 'asignaciones antenas',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='AsignacionBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.PositiveIntegerField(blank=True, null=True)),
                ('capex', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('cod_bodega', models.CharField(blank=True, max_length=255, null=True)),
                ('bodega', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario_bodega', models.CharField(blank=True, max_length=255, null=True)),
                ('so', models.CharField(blank=True, default='Bulk', max_length=255, null=True)),
                ('po', models.CharField(blank=True, default='Bulk', max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('parte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte')),
            ],
            options={
                'verbose_name': 'asignacion bulk',
                'verbose_name_plural': 'asignaciones bulk',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='EstadoPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_po', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('bts', models.PositiveIntegerField(blank=True, null=True)),
                ('bts_status', models.CharField(blank=True, max_length=255, null=True)),
                ('bts_arrival_week', models.PositiveIntegerField(blank=True, null=True)),
                ('jumper', models.CharField(blank=True, max_length=255, null=True)),
                ('jumper_status', models.CharField(blank=True, max_length=255, null=True)),
                ('jumper_arrival_week', models.PositiveIntegerField(blank=True, null=True)),
                ('fxcb_bts', models.CharField(blank=True, max_length=255, null=True)),
                ('fxcb_status', models.CharField(blank=True, max_length=255, null=True)),
                ('customs_ceared', models.CharField(blank=True, max_length=255, null=True)),
                ('sr', models.CharField(blank=True, max_length=255, null=True)),
                ('awb', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_pgi', models.CharField(blank=True, max_length=255, null=True)),
                ('fc_impl', models.PositiveIntegerField(blank=True, null=True)),
                ('fxcb_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('annotation', models.CharField(blank=True, max_length=255, null=True)),
                ('comprometido', models.CharField(blank=True, max_length=255, null=True)),
                ('share', models.CharField(blank=True, max_length=255, null=True)),
                ('w_reviewed', models.CharField(blank=True, max_length=255, null=True)),
                ('columna_924', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_po', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'estado po',
                'verbose_name_plural': 'estados po',
                'ordering': ('creado',),
            },
        ),
    ]
