# Generated by Django 2.0.7 on 2018-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopo',
            name='customs_ceared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadopo',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
