# Generated by Django 2.0.7 on 2018-07-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_auto_20180731_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopo',
            name='numero_po',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
