# Generated by Django 2.0.7 on 2018-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_auto_20180731_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopo',
            name='estacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
