# Generated by Django 2.0.7 on 2018-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_auto_20180801_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoZina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpo_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('so_jumper', models.PositiveIntegerField(blank=True, null=True)),
                ('so_bts', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_description', models.CharField(blank=True, max_length=255, null=True)),
                ('parte_capex', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'po zina',
                'verbose_name_plural': 'pos zina',
                'ordering': ('creado',),
            },
        ),
    ]
