# Generated by Django 2.0.7 on 2018-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_pozina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozina',
            name='cpo_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
