# Generated by Django 2.0.7 on 2018-08-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0030_proyeccionestacion'),
        ('asignaciones', '0007_auto_20180802_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioBolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitios_bolsa', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'sitio bolsa',
                'verbose_name_plural': 'sitios bolsa',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='SitioBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitios_bulk', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'sitio bulk',
                'verbose_name_plural': 'sitios bulk',
                'ordering': ('creado',),
            },
        ),
    ]
