# Generated by Django 2.0.7 on 2018-08-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0030_proyeccionestacion'),
        ('asignaciones', '0008_sitiobolsa_sitiobulk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.BigIntegerField(blank=True, null=True)),
                ('bts', models.PositiveIntegerField(blank=True, null=True)),
                ('bts_status', models.CharField(blank=True, max_length=255, null=True)),
                ('jumper', models.CharField(blank=True, max_length=255, null=True)),
                ('jumper_status', models.CharField(blank=True, max_length=255, null=True)),
                ('fxcb', models.CharField(blank=True, max_length=255, null=True)),
                ('fxcb_status', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitios_po', to='estaciones.Estacion')),
            ],
            options={
                'verbose_name': 'sitio po',
                'verbose_name_plural': 'sitios po',
                'ordering': ('creado',),
            },
        ),
        migrations.RemoveField(
            model_name='estadopo',
            name='fxcb_bts',
        ),
        migrations.AddField(
            model_name='estadopo',
            name='fxcb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
