# Generated by Django 2.0.7 on 2018-08-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0010_auto_20180808_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionbulk',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
