# Generated by Django 2.0.7 on 2018-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0011_auto_20180813_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionbulk',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
