# Generated by Django 2.0.7 on 2018-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0012_auto_20180813_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAntena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parte', models.CharField(blank=True, max_length=255, null=True)),
                ('cantiad_estimada', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('fc_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('familia', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('impacto', models.CharField(blank=True, max_length=255, null=True)),
                ('reserva', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_tss', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_antena', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
