# Generated by Django 2.0.7 on 2018-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0013_estadoantena'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoantena',
            name='estado_sitio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
