# Generated by Django 2.0.3 on 2018-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatoestacion',
            options={'ordering': ('creado',), 'verbose_name': 'formato estacion', 'verbose_name_plural': 'formatos estacion'},
        ),
        migrations.AlterModelOptions(
            name='formatoparte',
            options={'ordering': ('creado',), 'verbose_name': 'formato parte', 'verbose_name_plural': 'formatos parte'},
        ),
    ]
