# Generated by Django 2.0.3 on 2018-06-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20180615_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoestacion',
            name='estacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estaciones.Estacion'),
        ),
        migrations.AlterField(
            model_name='formatoparte',
            name='parte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte'),
        ),
    ]
