# Generated by Django 2.0.3 on 2018-06-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0005_formatoclaro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoclaro',
            name='formato_parte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatos.FormatoParte'),
        ),
        migrations.AlterField(
            model_name='formatoclaro',
            name='mes',
            field=models.CharField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=255, null=True),
        ),
    ]
