# Generated by Django 2.0.3 on 2018-06-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0007_auto_20180620_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoclaro',
            name='formato_parte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formatos.FormatoParte'),
        ),
    ]
