# Generated by Django 2.0.3 on 2018-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0009_formatoclaro_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoclaro',
            name='generado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
