# Generated by Django 2.0.3 on 2018-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0010_auto_20180621_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoclaro',
            name='id_sitio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
