# Generated by Django 2.0.3 on 2018-06-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_auto_20180516_0802'),
        ('formatos', '0011_formatoclaro_id_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoClaroTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.PositiveIntegerField(blank=True, null=True)),
                ('capex', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_parte', models.CharField(blank=True, choices=[('', '---------'), ('Accesorios', 'Accesorios'), ('Modulos', 'Modulos'), ('Antenas y Otros', 'Antenas y Otros')], max_length=255, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, editable=False)),
                ('subestado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('parte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partes.Parte')),
            ],
            options={
                'verbose_name': 'formato claro total',
                'verbose_name_plural': 'formatos claro total',
                'ordering': ('creado',),
            },
        ),
    ]
